<?php
	if(isset($this->view->err)){
		$err = $this->view->err;
	}
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>LOGIN</title>
	<link rel="stylesheet" type="text/css" href="public/css/login.css">
	<link rel="shortcut icon" href="https://img.icons8.com/pastel-glyph/64/000000/login-rounded-right.png">
	<!------------------------------------------------Bootstrap------------------------------------------------------>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
	<div class="form-box">
		<form class="form-container" method="post" action="">
			<div class="form-title">Login</div>
			<div class="form-group">
				<span class="badge badge-pill badge-danger"><?php if(isset($err)) echo $err; ?></span>
			</div>
		  <div class="form-group">
		    <label for="exampleInputEmail1">Email address</label>
		    <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" required placeholder="Email" value="<?php if(isset($_COOKIE['email'])){ echo $_COOKIE['email']; } ?>">
		    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Password</label>
		    <input type="password" class="form-control" name="password" id="exampleInputPassword1" required placeholder="Password">
		  </div>
		  <div class="form-group form-check">
		    <input type="checkbox" class="form-check-input" id="exampleCheck1" name="remember-me"
		    <?php
		    	if(isset($_COOKIE['email'])){
	    			echo "checked";
	    		}
		    ?>
		    >
		    <label class="form-check-label" for="exampleCheck1">Remember Me</label>
		  </div>
		  <button type="submit" class="btn btn-primary btn-block" name="login" value="login">LOGIN</button>
		</form>
	</div>

	<!------------------------------------------------Bootstrap------------------------------------------------->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>